name = "Odoocraft"
author = "Oppossome"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce3815a30acd6bdd3639dea0b3021dad1ef4e76869c6191f563e34a782535a85"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.253"
