name = "Odoocraft"
author = "Oppossome"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbd7e498248a4cb50f146c3a1e0c0c8c91d754ae00d1036413636c73ba8dde34"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.253"
